### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by mcleo-d** [finos-plexus/plexus-interop#152]
### Plexus demonstrates the following

- [ ] No OWASP Top 10 warnings are present in the code
- [ ] No long-standing medium or higher vulnerabilities (2+ months) 
- [ ] Proper security disclosure processes
- [ ] Any cryptographic functions and key lengths used within the software should be identified and vetted with Foundation's legal counsel in order to request compliance with U.S. Export policy.

**Comment by udalmik** [comment]
Repo is integrated with WhiteSource tool, therefore:

**No OWASP Top 10 warnings are present in the code**
No warnings

 **No long-standing medium or higher vulnerabilities (2+ months)**
No long-standing valnurabilities

**Proper security disclosure processes**
Proactive raise of vulnerabilities by Whitesource tool
 
**Any cryptographic functions and key lengths used within the software should be identified and vetted with Foundation's legal counsel in order to request compliance with U.S. Export policy.**
Not applicable
